export const NAME = 'Nome';
export const STATUS = 'Status';
export const ACTIONS = 'Ações';
export const BRAND = 'Bandeira';
export const NEW_CARD = 'Novo Cartão';
export const EDIT_CARD = 'Editar Cartão';
export const REGISTER_NEW = 'Cadastrar Novo';
export const THE_CARD_NAME_IS_REQUIRED = 'O nome do cartão é obrigatório';
export const THE_CARD_NETWORK_IS_MANDATORY = 'A bandeira do cartão é obrigatória';
